package fi.vesas.jdbcprof.capture;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;
import java.util.function.Supplier;

/**
 * Wraps a real {@link Connection} so that the statements it produces
 * — and the transaction events it signals — are captured (spec §5.1).
 *
 * <p>Only the methods named in spec §5.1 are intercepted
 * ({@code prepareStatement}, {@code createStatement}, {@code commit},
 * {@code rollback}, {@code close}). Every other method is straight
 * delegation to the underlying connection.
 *
 * <p>The {@link CaptureContext} is resolved per call via the supplier
 * so a connection produced before {@code Profiler.start()} still
 * captures once a session becomes active. When no session is active
 * capture methods delegate without so much as a {@code nanoTime()}.
 *
 * <p>{@code prepareStatement} interns the SQL template at prepare
 * time whenever a session is active. When no session is active at
 * prepare time, the raw template is handed to
 * {@link CapturingPreparedStatement} which interns lazily on first
 * execute — this keeps intern ids stable across the lifetime of one
 * statement while avoiding work when profiling is off.
 */
final class CapturingConnection implements Connection {

    private static final byte PREPARE = (byte) EventType.PREPARE.ordinal();
    private static final byte COMMIT = (byte) EventType.COMMIT.ordinal();
    private static final byte ROLLBACK = (byte) EventType.ROLLBACK.ordinal();
    private static final byte CLOSE = (byte) EventType.CLOSE.ordinal();

    private final Connection delegate;
    private final Supplier<CaptureContext> ctxSupplier;

    CapturingConnection(Connection delegate, Supplier<CaptureContext> ctxSupplier) {
        this.delegate = delegate;
        this.ctxSupplier = ctxSupplier;
    }

    private CapturingPreparedStatement wrapPrepared(PreparedStatement real, String sql,
                                                    long t0, long t1, CaptureContext ctx)
            throws SQLException {
        if (ctx == null) {
            return new CapturingPreparedStatement(real, ctxSupplier, sql, -1);
        }
        int sqlId = ctx.sqlIntern().intern(sql);
        ctx.emit(PREPARE, sqlId, t0, t1 - t0, -1, 0, 0L);
        return new CapturingPreparedStatement(real, ctxSupplier, sql, sqlId);
    }

    @Override
    public Statement createStatement() throws SQLException {
        return new CapturingStatement(delegate.createStatement(), ctxSupplier);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return new CapturingStatement(
                delegate.createStatement(resultSetType, resultSetConcurrency), ctxSupplier);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency,
                                     int resultSetHoldability) throws SQLException {
        return new CapturingStatement(
                delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability),
                ctxSupplier);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return new CapturingPreparedStatement(delegate.prepareStatement(sql),
                    ctxSupplier, sql, -1);
        }
        long t0 = System.nanoTime();
        PreparedStatement real = delegate.prepareStatement(sql);
        long t1 = System.nanoTime();
        return wrapPrepared(real, sql, t0, t1, ctx);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return new CapturingPreparedStatement(
                    delegate.prepareStatement(sql, autoGeneratedKeys), ctxSupplier, sql, -1);
        }
        long t0 = System.nanoTime();
        PreparedStatement real = delegate.prepareStatement(sql, autoGeneratedKeys);
        long t1 = System.nanoTime();
        return wrapPrepared(real, sql, t0, t1, ctx);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return new CapturingPreparedStatement(
                    delegate.prepareStatement(sql, columnIndexes), ctxSupplier, sql, -1);
        }
        long t0 = System.nanoTime();
        PreparedStatement real = delegate.prepareStatement(sql, columnIndexes);
        long t1 = System.nanoTime();
        return wrapPrepared(real, sql, t0, t1, ctx);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return new CapturingPreparedStatement(
                    delegate.prepareStatement(sql, columnNames), ctxSupplier, sql, -1);
        }
        long t0 = System.nanoTime();
        PreparedStatement real = delegate.prepareStatement(sql, columnNames);
        long t1 = System.nanoTime();
        return wrapPrepared(real, sql, t0, t1, ctx);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType,
                                              int resultSetConcurrency) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return new CapturingPreparedStatement(
                    delegate.prepareStatement(sql, resultSetType, resultSetConcurrency),
                    ctxSupplier, sql, -1);
        }
        long t0 = System.nanoTime();
        PreparedStatement real = delegate.prepareStatement(sql, resultSetType, resultSetConcurrency);
        long t1 = System.nanoTime();
        return wrapPrepared(real, sql, t0, t1, ctx);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType,
                                              int resultSetConcurrency,
                                              int resultSetHoldability) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return new CapturingPreparedStatement(
                    delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability),
                    ctxSupplier, sql, -1);
        }
        long t0 = System.nanoTime();
        PreparedStatement real = delegate.prepareStatement(sql, resultSetType,
                resultSetConcurrency, resultSetHoldability);
        long t1 = System.nanoTime();
        return wrapPrepared(real, sql, t0, t1, ctx);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        return delegate.prepareCall(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType,
                                         int resultSetConcurrency) throws SQLException {
        return delegate.prepareCall(sql, resultSetType, resultSetConcurrency);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType,
                                         int resultSetConcurrency,
                                         int resultSetHoldability) throws SQLException {
        return delegate.prepareCall(sql, resultSetType,
                resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public void commit() throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            delegate.commit();
            return;
        }
        long t0 = System.nanoTime();
        delegate.commit();
        long t1 = System.nanoTime();
        ctx.emit(COMMIT, -1, t0, t1 - t0, -1, 0, 0L);
    }

    @Override
    public void rollback() throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            delegate.rollback();
            return;
        }
        long t0 = System.nanoTime();
        delegate.rollback();
        long t1 = System.nanoTime();
        ctx.emit(ROLLBACK, -1, t0, t1 - t0, -1, 0, 0L);
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            delegate.rollback(savepoint);
            return;
        }
        long t0 = System.nanoTime();
        delegate.rollback(savepoint);
        long t1 = System.nanoTime();
        ctx.emit(ROLLBACK, -1, t0, t1 - t0, -1, 0, 0L);
    }

    @Override
    public void close() throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            delegate.close();
            return;
        }
        long t0 = System.nanoTime();
        delegate.close();
        long t1 = System.nanoTime();
        ctx.emit(CLOSE, -1, t0, t1 - t0, -1, 0, 0L);
    }

    // --- everything below is straight delegation ---

    @Override public String nativeSQL(String sql) throws SQLException { return delegate.nativeSQL(sql); }
    @Override public void setAutoCommit(boolean autoCommit) throws SQLException { delegate.setAutoCommit(autoCommit); }
    @Override public boolean getAutoCommit() throws SQLException { return delegate.getAutoCommit(); }
    @Override public boolean isClosed() throws SQLException { return delegate.isClosed(); }
    @Override public DatabaseMetaData getMetaData() throws SQLException { return delegate.getMetaData(); }
    @Override public void setReadOnly(boolean readOnly) throws SQLException { delegate.setReadOnly(readOnly); }
    @Override public boolean isReadOnly() throws SQLException { return delegate.isReadOnly(); }
    @Override public void setCatalog(String catalog) throws SQLException { delegate.setCatalog(catalog); }
    @Override public String getCatalog() throws SQLException { return delegate.getCatalog(); }
    @Override public void setTransactionIsolation(int level) throws SQLException { delegate.setTransactionIsolation(level); }
    @Override public int getTransactionIsolation() throws SQLException { return delegate.getTransactionIsolation(); }
    @Override public SQLWarning getWarnings() throws SQLException { return delegate.getWarnings(); }
    @Override public void clearWarnings() throws SQLException { delegate.clearWarnings(); }
    @Override public Map<String, Class<?>> getTypeMap() throws SQLException { return delegate.getTypeMap(); }
    @Override public void setTypeMap(Map<String, Class<?>> map) throws SQLException { delegate.setTypeMap(map); }
    @Override public void setHoldability(int holdability) throws SQLException { delegate.setHoldability(holdability); }
    @Override public int getHoldability() throws SQLException { return delegate.getHoldability(); }
    @Override public Savepoint setSavepoint() throws SQLException { return delegate.setSavepoint(); }
    @Override public Savepoint setSavepoint(String name) throws SQLException { return delegate.setSavepoint(name); }
    @Override public void releaseSavepoint(Savepoint savepoint) throws SQLException { delegate.releaseSavepoint(savepoint); }
    @Override public Clob createClob() throws SQLException { return delegate.createClob(); }
    @Override public Blob createBlob() throws SQLException { return delegate.createBlob(); }
    @Override public NClob createNClob() throws SQLException { return delegate.createNClob(); }
    @Override public SQLXML createSQLXML() throws SQLException { return delegate.createSQLXML(); }
    @Override public boolean isValid(int timeout) throws SQLException { return delegate.isValid(timeout); }
    @Override public void setClientInfo(String name, String value) throws SQLClientInfoException { delegate.setClientInfo(name, value); }
    @Override public void setClientInfo(Properties properties) throws SQLClientInfoException { delegate.setClientInfo(properties); }
    @Override public String getClientInfo(String name) throws SQLException { return delegate.getClientInfo(name); }
    @Override public Properties getClientInfo() throws SQLException { return delegate.getClientInfo(); }
    @Override public Array createArrayOf(String typeName, Object[] elements) throws SQLException { return delegate.createArrayOf(typeName, elements); }
    @Override public Struct createStruct(String typeName, Object[] attributes) throws SQLException { return delegate.createStruct(typeName, attributes); }
    @Override public void setSchema(String schema) throws SQLException { delegate.setSchema(schema); }
    @Override public String getSchema() throws SQLException { return delegate.getSchema(); }
    @Override public void abort(Executor executor) throws SQLException { delegate.abort(executor); }
    @Override public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException { delegate.setNetworkTimeout(executor, milliseconds); }
    @Override public int getNetworkTimeout() throws SQLException { return delegate.getNetworkTimeout(); }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) {
            return iface.cast(this);
        }
        return delegate.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isInstance(this) || delegate.isWrapperFor(iface);
    }
}
