package fi.vesas.jdbcprof.capture;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;
import java.util.function.Supplier;

/**
 * Wraps a real {@link Statement} so that ad-hoc SQL execution,
 * batching, and close are captured (spec §5.1, §5.5). Non-final so
 * {@link CapturingPreparedStatement} can extend it.
 *
 * <p>The {@link CaptureContext} is resolved per call via the supplier.
 * When no session is active the capture methods are a delegate-only
 * fast path — no interning, no nanoTime, no event emission.
 *
 * <p>SQL supplied to the ad-hoc {@code execute*} methods is
 * normalised to template form via {@link SqlTemplateNormalizer} before
 * interning. For each execution, the {@code sqlId} of the last
 * template is remembered on {@link #lastSqlId} so any {@link ResultSet}
 * the caller retrieves via {@link #getResultSet()} can attribute its
 * {@code next()} events to the right template. When the executing
 * session was inactive, {@code lastSqlId} stays {@code -1} and the
 * result set wrapper skips emission accordingly.
 */
class CapturingStatement implements Statement {

    private static final byte EXECUTE_QUERY = (byte) EventType.EXECUTE_QUERY.ordinal();
    private static final byte EXECUTE_UPDATE = (byte) EventType.EXECUTE_UPDATE.ordinal();
    private static final byte EXECUTE_BATCH = (byte) EventType.EXECUTE_BATCH.ordinal();
    private static final byte CLOSE = (byte) EventType.CLOSE.ordinal();

    final Statement delegate;
    final Supplier<CaptureContext> ctxSupplier;

    int lastSqlId = -1;
    int batchSize = 0;

    CapturingStatement(Statement delegate, Supplier<CaptureContext> ctxSupplier) {
        this.delegate = delegate;
        this.ctxSupplier = ctxSupplier;
    }

    static int internAdHoc(CaptureContext ctx, String raw) {
        return ctx.sqlIntern().intern(SqlTemplateNormalizer.normalize(raw));
    }

    ResultSet wrapResultSet(ResultSet rs) {
        if (rs == null) {
            return null;
        }
        return new CapturingResultSet(rs, ctxSupplier, lastSqlId);
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return wrapResultSet(delegate.executeQuery(sql));
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        ResultSet rs = delegate.executeQuery(sql);
        long t1 = System.nanoTime();
        ctx.emit(EXECUTE_QUERY, id, t0, t1 - t0, -1, 0, 0L);
        return wrapResultSet(rs);
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return delegate.executeUpdate(sql);
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        int rows = delegate.executeUpdate(sql);
        long t1 = System.nanoTime();
        ctx.emit(EXECUTE_UPDATE, id, t0, t1 - t0, rows, 0, 0L);
        return rows;
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return delegate.executeUpdate(sql, autoGeneratedKeys);
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        int rows = delegate.executeUpdate(sql, autoGeneratedKeys);
        long t1 = System.nanoTime();
        ctx.emit(EXECUTE_UPDATE, id, t0, t1 - t0, rows, 0, 0L);
        return rows;
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return delegate.executeUpdate(sql, columnIndexes);
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        int rows = delegate.executeUpdate(sql, columnIndexes);
        long t1 = System.nanoTime();
        ctx.emit(EXECUTE_UPDATE, id, t0, t1 - t0, rows, 0, 0L);
        return rows;
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return delegate.executeUpdate(sql, columnNames);
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        int rows = delegate.executeUpdate(sql, columnNames);
        long t1 = System.nanoTime();
        ctx.emit(EXECUTE_UPDATE, id, t0, t1 - t0, rows, 0, 0L);
        return rows;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return delegate.execute(sql);
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        boolean hasResultSet = delegate.execute(sql);
        long t1 = System.nanoTime();
        emitExecuteUnknown(ctx, id, t0, t1, hasResultSet);
        return hasResultSet;
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return delegate.execute(sql, autoGeneratedKeys);
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        boolean hasResultSet = delegate.execute(sql, autoGeneratedKeys);
        long t1 = System.nanoTime();
        emitExecuteUnknown(ctx, id, t0, t1, hasResultSet);
        return hasResultSet;
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return delegate.execute(sql, columnIndexes);
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        boolean hasResultSet = delegate.execute(sql, columnIndexes);
        long t1 = System.nanoTime();
        emitExecuteUnknown(ctx, id, t0, t1, hasResultSet);
        return hasResultSet;
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return delegate.execute(sql, columnNames);
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        boolean hasResultSet = delegate.execute(sql, columnNames);
        long t1 = System.nanoTime();
        emitExecuteUnknown(ctx, id, t0, t1, hasResultSet);
        return hasResultSet;
    }

    final void emitExecuteUnknown(CaptureContext ctx, int sqlId, long t0, long t1,
                                  boolean hasResultSet) throws SQLException {
        emitExecuteUnknown(ctx, sqlId, t0, t1, hasResultSet, 0L);
    }

    final void emitExecuteUnknown(CaptureContext ctx, int sqlId, long t0, long t1,
                                  boolean hasResultSet, long parameterFingerprint) throws SQLException {
        if (hasResultSet) {
            ctx.emit(EXECUTE_QUERY, sqlId, t0, t1 - t0, -1, 0, parameterFingerprint);
        } else {
            int rows = delegate.getUpdateCount();
            ctx.emit(EXECUTE_UPDATE, sqlId, t0, t1 - t0, rows, 0, parameterFingerprint);
        }
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx != null) {
            // Spec §5.3: batch members are counted, not individually recorded.
            // Still intern the last member's template so the batch event
            // has a representative sqlId for grouping.
            lastSqlId = internAdHoc(ctx, sql);
        }
        delegate.addBatch(sql);
        batchSize++;
    }

    @Override
    public void clearBatch() throws SQLException {
        delegate.clearBatch();
        batchSize = 0;
    }

    @Override
    public int[] executeBatch() throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            int[] counts = delegate.executeBatch();
            batchSize = 0;
            return counts;
        }
        int size = batchSize;
        int id = lastSqlId;
        long t0 = System.nanoTime();
        int[] counts = delegate.executeBatch();
        long t1 = System.nanoTime();
        ctx.emit(EXECUTE_BATCH, id, t0, t1 - t0, -1, size, 0L);
        batchSize = 0;
        return counts;
    }

    @Override
    public long[] executeLargeBatch() throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            long[] counts = delegate.executeLargeBatch();
            batchSize = 0;
            return counts;
        }
        int size = batchSize;
        int id = lastSqlId;
        long t0 = System.nanoTime();
        long[] counts = delegate.executeLargeBatch();
        long t1 = System.nanoTime();
        ctx.emit(EXECUTE_BATCH, id, t0, t1 - t0, -1, size, 0L);
        batchSize = 0;
        return counts;
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return delegate.executeLargeUpdate(sql);
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        long rows = delegate.executeLargeUpdate(sql);
        long t1 = System.nanoTime();
        ctx.emit(EXECUTE_UPDATE, id, t0, t1 - t0, clampRows(rows), 0, 0L);
        return rows;
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return delegate.executeLargeUpdate(sql, autoGeneratedKeys);
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        long rows = delegate.executeLargeUpdate(sql, autoGeneratedKeys);
        long t1 = System.nanoTime();
        ctx.emit(EXECUTE_UPDATE, id, t0, t1 - t0, clampRows(rows), 0, 0L);
        return rows;
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return delegate.executeLargeUpdate(sql, columnIndexes);
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        long rows = delegate.executeLargeUpdate(sql, columnIndexes);
        long t1 = System.nanoTime();
        ctx.emit(EXECUTE_UPDATE, id, t0, t1 - t0, clampRows(rows), 0, 0L);
        return rows;
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            return delegate.executeLargeUpdate(sql, columnNames);
        }
        int id = internAdHoc(ctx, sql);
        lastSqlId = id;
        long t0 = System.nanoTime();
        long rows = delegate.executeLargeUpdate(sql, columnNames);
        long t1 = System.nanoTime();
        ctx.emit(EXECUTE_UPDATE, id, t0, t1 - t0, clampRows(rows), 0, 0L);
        return rows;
    }

    static int clampRows(long rows) {
        if (rows > Integer.MAX_VALUE) return Integer.MAX_VALUE;
        if (rows < Integer.MIN_VALUE) return Integer.MIN_VALUE;
        return (int) rows;
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        return wrapResultSet(delegate.getResultSet());
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        // Generated-keys cursors are rarely iterated for hot-path N+1; wrap
        // anyway so NEXT events on them attribute to the producing statement.
        return wrapResultSet(delegate.getGeneratedKeys());
    }

    @Override
    public void close() throws SQLException {
        CaptureContext ctx = ctxSupplier.get();
        if (ctx == null) {
            delegate.close();
            return;
        }
        long t0 = System.nanoTime();
        delegate.close();
        long t1 = System.nanoTime();
        // Lifetime-boundary marker. Skip the stack walk — see
        // CaptureContext#emitNoTrace.
        ctx.emitNoTrace(CLOSE, -1, t0, t1 - t0, -1, 0, 0L);
    }

    // --- everything below is straight delegation ---

    @Override public int getMaxFieldSize() throws SQLException { return delegate.getMaxFieldSize(); }
    @Override public void setMaxFieldSize(int max) throws SQLException { delegate.setMaxFieldSize(max); }
    @Override public int getMaxRows() throws SQLException { return delegate.getMaxRows(); }
    @Override public void setMaxRows(int max) throws SQLException { delegate.setMaxRows(max); }
    @Override public void setEscapeProcessing(boolean enable) throws SQLException { delegate.setEscapeProcessing(enable); }
    @Override public int getQueryTimeout() throws SQLException { return delegate.getQueryTimeout(); }
    @Override public void setQueryTimeout(int seconds) throws SQLException { delegate.setQueryTimeout(seconds); }
    @Override public void cancel() throws SQLException { delegate.cancel(); }
    @Override public SQLWarning getWarnings() throws SQLException { return delegate.getWarnings(); }
    @Override public void clearWarnings() throws SQLException { delegate.clearWarnings(); }
    @Override public void setCursorName(String name) throws SQLException { delegate.setCursorName(name); }
    @Override public int getUpdateCount() throws SQLException { return delegate.getUpdateCount(); }
    @Override public boolean getMoreResults() throws SQLException { return delegate.getMoreResults(); }
    @Override public boolean getMoreResults(int current) throws SQLException { return delegate.getMoreResults(current); }
    @Override public void setFetchDirection(int direction) throws SQLException { delegate.setFetchDirection(direction); }
    @Override public int getFetchDirection() throws SQLException { return delegate.getFetchDirection(); }
    @Override public void setFetchSize(int rows) throws SQLException { delegate.setFetchSize(rows); }
    @Override public int getFetchSize() throws SQLException { return delegate.getFetchSize(); }
    @Override public int getResultSetConcurrency() throws SQLException { return delegate.getResultSetConcurrency(); }
    @Override public int getResultSetType() throws SQLException { return delegate.getResultSetType(); }
    @Override public Connection getConnection() throws SQLException { return delegate.getConnection(); }
    @Override public int getResultSetHoldability() throws SQLException { return delegate.getResultSetHoldability(); }
    @Override public boolean isClosed() throws SQLException { return delegate.isClosed(); }
    @Override public void setPoolable(boolean poolable) throws SQLException { delegate.setPoolable(poolable); }
    @Override public boolean isPoolable() throws SQLException { return delegate.isPoolable(); }
    @Override public void closeOnCompletion() throws SQLException { delegate.closeOnCompletion(); }
    @Override public boolean isCloseOnCompletion() throws SQLException { return delegate.isCloseOnCompletion(); }
    @Override public long getLargeUpdateCount() throws SQLException { return delegate.getLargeUpdateCount(); }
    @Override public void setLargeMaxRows(long max) throws SQLException { delegate.setLargeMaxRows(max); }
    @Override public long getLargeMaxRows() throws SQLException { return delegate.getLargeMaxRows(); }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) {
            return iface.cast(this);
        }
        return delegate.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isInstance(this) || delegate.isWrapperFor(iface);
    }
}
